name: Generar Clips desde YouTube

on:
  workflow_dispatch: # Permite ejecutarlo manualmente
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente a medianoche (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Instalar FFmpeg (¡CRUCIAL!)
      run: sudo apt-get install -y ffmpeg

    - name: Ejecutar script de descarga
      run: python src/download.py

    - name: Generar clips
      run: python src/clip_generator.py

    - name: Subir clips generados
      uses: actions/upload-artifact@v4
      with:
        name: clips-generados
        path: | 
          *.mp4
          !video_descargado.mp4
