name: Generar Clips desde YouTube

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Crear carpetas necesarias
      run: |
        mkdir -p clips downloads

    - name: Generar clips
      run: python src/clip_generator.py

    - name: Subir clips generados
      uses: actions/upload-artifact@v4
      with:
        name: clips-generados
        path: clips/
