name: YouTube Clip Generator

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube URL'
        required: true

jobs:
  generate-clip:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install yt-dlp openai-whisper moviepy pandas numpy
        pip install tenacity  # 👈 Agregar esta línea
    
    - name: Setup cookies
      run: |
        if [ -n "${{ secrets.YOUTUBE_COOKIES }}" ]; then
          echo "${{ secrets.YOUTUBE_COOKIES }}" | base64 -d > cookies.txt
        fi
    
    - name: Run clip generator
      run: |
        python src/clip_generator.py "${{ github.event.inputs.youtube_url }}"
      env:
        YOUTUBE_URL: "${{ github.event.inputs.youtube_url }}"
    
    - name: Upload generated clips
      uses: actions/upload-artifact@v3
      with:
        name: generated-clips
        path: outputs/
